# Generated by Django 4.0.1 on 2022-02-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_arrival',
            new_name='All_time_special',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
        migrations.AddField(
            model_name='product',
            name='Todays_detail',
            field=models.BooleanField(default=False, help_text='0=defeault, 1=Todays_detail'),
        ),
    ]
