from django.urls import path
from app import views
from app.controller import authview
urlpatterns = [
     path('', views.home),
    #  path('product-detail/', views.product_detail, name='product-detail'),
    path('cart/', views.cart, name='cart'),
    path('buy/', views.buy_now, name='buy-now'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('orders/', views.order, name='orders'),
    path('order_placed/', views.order_placed, name='order_placed'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('burger/', views.burger, name='burger'),
    path('pizza/', views.pizza, name='pizza'),
    path('momo/', views.momo, name='momo'),
    path('chicken/', views.chicken, name='chicken'),
    path('alcohol/', views.alcohol, name='alcohol'),
    path('beer/', views.beer, name='beer'),
    path('wine/', views.wine, name='wine'),
    path('login/', authview.loginpage, name='loginpage'),
    path('registration/', authview.register, name='customerregistration'),
    path('logout/', authview.logoutpage, name='logout'),
    path('checkout/', views.checkout, name='checkout'),
    path('products/<int:myid>', views.productview, name="products"),
    path('burger/products/<int:myid>', views.productview, name="products"),
    path('pizza/products/<int:myid>', views.productview, name="products"),
    path('chicken/products/<int:myid>', views.productview, name="products"),
    path('update_item/',views.update_item,name="update_item"),
    path('momo/<int:myid>', views.productview, name="products"),
    path('plus_cart/', views.plus_cart),
    path('minus_cart/', views.minus_cart),
    path('remove_cart/', views.remove_cart),
    # path('custom_admin',views.custom_admin,name="custom_admin"),
    path('admin_cart/',views.admin_cart,name="admin_cart"),
    path('admin_category/',views.admin_category,name="admin_category"),
    path('admin_order/',views.admin_order,name="admin_order"),
    path('admin_product/',views.admin_product,name="admin_product"),
]
