from django.urls import path
from app import views
from app.controller import authview
urlpatterns = [
     path('', views.home),
    #  path('product-detail/', views.product_detail, name='product-detail'),
    path('cart/', views.add_to_cart, name='add-to-cart'),
    path('buy/', views.buy_now, name='buy-now'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('orders/', views.orders, name='orders'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('burger/', views.burger, name='burger'),
    path('pizza/', views.pizza, name='pizza'),
    path('momo/', views.momo, name='momo'),
    path('chicken/', views.chicken, name='chicken'),
    path('alcohol/', views.alcohol, name='alcohol'),
    path('beer/', views.beer, name='beer'),
    path('wine/', views.wine, name='wine'),
    path('login/', authview.loginpage, name='loginpage'),
    path('registration/', authview.register, name='customerregistration'),
    path('logout/', authview.logoutpage, name='logout'),
    path('checkout/', views.checkout, name='checkout'),
    path('products/<int:myid>', views.productview, name="products"),
    path('burger/products/<int:myid>', views.productview, name="products"),
    path('pizza/products/<int:myid>', views.productview, name="products"),
    path('pizza/products/<int:myid>', views.productview, name="products"),
    path('chicken/products/<int:myid>', views.productview, name="products"),
    path('momo/<int:myid>', views.productview, name="products"),
]
